"""
fix_pr_service.py  (app.fixes)
==============================
Stage 8.14 — Fix PR Creation Service.

Publishes an AI-generated code fix as a Pull Request on GitHub.

Design principles (Phase 8 spec §17):
    1. Only COMMITTED / APPROVED fix requests can have PRs created.
    2. Standardized PR Title: ``[AI Auto-Fix] {issue_title} ({category})``
    3. Structured PR Body including:
       - Finding details (title, description, suggestion).
       - Changed file and modified lines.
       - AI fix explanation.
       - Mandatory Safety Notice: "Preview & human approval complete. Never automatically merged."
    4. Safety Invariants:
       - NEVER automatically merge a generated PR.
       - Autonomous self-merging is strictly FORBIDDEN in Phase 8.
    5. Status advances to PR_CREATED upon success.

Author : AI Code Review Bot — Phase 8 (Stage 8.14)
"""

from __future__ import annotations

import logging
from dataclasses import dataclass
from typing import Optional

from app.fixes.branch_service import generate_branch_name
from app.fixes.exceptions import FixNotFoundError, FixStateError, FixValidationError
from app.fixes.fix_service import _FIX_PATCH_STORE, _FIX_REQUEST_STORE
from app.fixes.models import FixPatch, FixRequest, FixStatus
from app.github.github_fix_service import GitHubFixService

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Data Models
# ---------------------------------------------------------------------------


@dataclass(frozen=True)
class FixPRResult:
    """Outcome of publishing an AI Fix Pull Request on GitHub.

    Attributes:
        fix_request_id : Target FixRequest ID.
        pr_number      : Created PR number.
        pr_url         : HTML URL to the created PR.
        head_branch    : Fix branch containing the patch.
        base_branch    : Target branch for PR merge.
        title          : PR title.
    """

    fix_request_id: str
    pr_number: int
    pr_url: str
    head_branch: str
    base_branch: str
    title: str


# ---------------------------------------------------------------------------
# PR Body Formatter Helper
# ---------------------------------------------------------------------------


def format_fix_pr_body(fix_req: FixRequest, patch: Optional[FixPatch] = None) -> str:
    """Format structured PR body markdown for an AI Fix Pull Request."""
    category_slug = fix_req.issue_id.split("-")[0].capitalize()
    req_short = (fix_req.id or "00000000")[:8]

    sections: list[str] = [
        "## 🤖 AI Code Remediation Proposal",
        "",
        f"This Pull Request contains an automated code fix proposal generated for Issue **`{fix_req.issue_id}`**.",
        "",
        "### 📌 Finding Details",
        f"- **Category:** `{category_slug}`",
        f"- **Finding Title:** {fix_req.issue_title}",
        f"- **Target File:** `{fix_req.file_path}`",
        f"- **Target Line:** {fix_req.line or 'N/A'}",
        f"- **Original Review ID:** `{fix_req.review_id}`",
        "",
        "### 📝 Description of Problem",
        fix_req.issue_description,
        "",
        "### 💡 Original Recommendation",
        fix_req.suggestion or "No specific suggestion provided.",
    ]

    if patch and patch.explanation:
        sections.extend([
            "",
            "### 🛠️ Remediation Summary",
            patch.explanation,
        ])

    sections.extend([
        "",
        "---",
        "### ⚠️ Safety & Governance Notice",
        "> [!IMPORTANT]",
        "> This PR was generated by the AI Code Remediation Engine following developer preview and explicit approval.",
        "> **Autonomous self-merging is strictly disabled.** Never automatically merged. A human reviewer must inspect and merge this PR.",
        "",
        f"_Generated by Automated Code Review Bot (Fix Request ID: `{req_short}`)_",
    ])


    return "\n".join(sections)


# ---------------------------------------------------------------------------
# FixPRService
# ---------------------------------------------------------------------------


class FixPRService:
    """Service handling Pull Request creation for approved and committed fixes.

    Args:
        github_fix_service : Service for issuing low-level GitHub PR API calls.
    """

    def __init__(self, github_fix_service: GitHubFixService) -> None:
        self._gh_fix_svc = github_fix_service

    async def create_fix_pr(
        self,
        fix_request_id: str,
        target_base_branch: Optional[str] = None,
        draft: bool = False,
    ) -> FixPRResult:
        """Create a Pull Request on GitHub for an APPROVED/COMMITTED FixRequest.

        Args:
            fix_request_id     : Unique FixRequest ID.
            target_base_branch : Base branch for PR target (defaults to default branch or 'main').
            draft              : If True, creates PR as a draft PR.

        Returns:
            FixPRResult containing PR number and URL.

        Raises:
            FixNotFoundError   : If FixRequest does not exist.
            FixStateError      : If status is not COMMITTED or APPROVED.
            FixValidationError : If GitHub PR creation fails.
        """
        logger.info("Initiating PR creation for fix request %s", fix_request_id)

        # ── 1. Fetch FixRequest & Patch ───────────────────────────────
        fix_req = _FIX_REQUEST_STORE.get(fix_request_id)
        if not fix_req:
            raise FixNotFoundError(f"Fix request '{fix_request_id}' was not found.")

        current_status = fix_req.status.value if hasattr(fix_req.status, "value") else str(fix_req.status)
        if current_status not in (FixStatus.COMMITTED.value, FixStatus.APPROVED.value, FixStatus.APPLYING.value):
            raise FixStateError(
                f"Cannot create PR for fix request '{fix_request_id}' in state '{current_status}'. "
                "Fix request must be COMMITTED or APPROVED."
            )

        patch = _FIX_PATCH_STORE.get(fix_request_id)
        owner, repo = fix_req.repository.split("/", 1)

        head_branch = generate_branch_name(fix_req)
        base_branch = target_base_branch or "main"

        # ── 2. Format Title & Body ─────────────────────────────────────
        category_slug = fix_req.issue_id.split("-")[0].capitalize()
        pr_title = f"[AI Auto-Fix] {fix_req.issue_title} ({category_slug})"
        pr_body = format_fix_pr_body(fix_req, patch)

        # ── 3. Call GitHub API to Create PR ───────────────────────────
        pr_number, pr_url = await self._gh_fix_svc.create_fix_pull_request(
            owner=owner,
            repo=repo,
            title=pr_title,
            body=pr_body,
            head_branch=head_branch,
            base_branch=base_branch,
            draft=draft,
        )

        # Advance status to PR_CREATED
        fix_req.status = FixStatus.PR_CREATED
        _FIX_REQUEST_STORE[fix_req.id] = fix_req

        logger.info(
            "Fix PR #%d created successfully for %s: url=%s",
            pr_number,
            fix_req.id,
            pr_url,
        )

        return FixPRResult(
            fix_request_id=fix_req.id,
            pr_number=pr_number,
            pr_url=pr_url,
            head_branch=head_branch,
            base_branch=base_branch,
            title=pr_title,
        )
